
import serial.tools.list_ports
import pyvisa
import os
import sys
from pathlib import Path
import json
import subprocess

##### import project related moduls ####
current_file = Path(__file__).resolve()
project_root = current_file.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils.terminal_styler import TerminalColours


class BaseDevice(TerminalColours):

    CONNECTION_SETTINGS = {}


    def __init__(self):
        self.rm = None

        config_path = Path(__file__).parent / "devices_config.json"
        self.DEVICE_DIKT = self._load_device_config(config_path)

        try:
            self.rm = pyvisa.ResourceManager()
        except Exception:
            print(self.RED)
            print("BaseDevice init Error, pyvisa.ResourceManager() not created")
            print("VISA not installed?")
            print(self.RESET)
        self.hwid = None # HardWare IDentification  
        self.name = None
        self.port = None
     #   self.connection = None # the property for protection
        self.__inst = None

    def _load_device_config(self, path): 
        ''' Loads the hardware IDs from the JSON file '''
        try: 
            with open(path, 'r') as f: 
                config = json.load(f)
                flat_dict = {}
                for category in config.values():
                    flat_dict.update(category)
                return flat_dict
        except Exception as e: 
            print(f"{self.RED}Error loading config file {path}: {e}{self.RESET}")
            return {}

    @property
    def connection(self):
        if self.__inst is None:
            print(f"\n [{self.name}]BaseDevice.connection")
            print(f"{self.RED}Device is not connected{self.RESET}")
            # raise ConnectionError(f"{self.RED}Device is not connected{self.RESET}")
        return self.__inst
    

    def print_com_info(self):
        ports = serial.tools.list_ports.comports()
        print(" BaseDevice.print_com_info ".center(50, '-'))
        print(f"{self.CYAN}{'-' * 50}{self.RESET}")
        for port in ports:
            print(f"=== Port: {port.device} ===")
            # vars(port) returns a dict of all the object's internal variables
            for key, value in vars(port).items():
                print(f"  {key}: {value}")
            print(f"{self.CYAN}{'-' * 50}{self.RESET}")
        return self


    def _is_windows_serial_fake(self, port, silent=False):
        """
        Queries Windows if the serial number of a device is generated or read from the hardware.
        """
        result = None
        if os.name != "nt":
            print(f"{self.RED} _is_windows_serial_fake() is only implemented for Windows OS. {self.RESET}")
            return None
            
        try:
            # Query Windows Management Instrumentation for the specific COM port
            cmd = f'wmic path Win32_PnPEntity where "Caption like \'%({port.device})%\'" get PNPDeviceID'
            
            # Run the command silently via subprocess
            output = subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.DEVNULL)
            wmic_ser = output.split("\\")[-1].strip()  # Get the second line which contains the PNPDeviceID
            
            if wmic_ser == port.serial_number:
                result = False  # Serial number is real, read from hardware
            else:
                result = True   # Serial number is fake, generated by Windows

            if not silent:
                print()
                print(f"--- Checking if serial number for {port.device} is fake ---")
                print(f"{output=}")
                print(f"{wmic_ser=}")
                print(f"{port.serial_number=}")
                print(f"Is serial number fake?: {result=}")
            
        except Exception:
            print(f" {self.RED} Error occurred while querying Windows for port {port.device} {self.RESET}")
        
            
        return result

        
    def _get_COM_connections(self):
        device_list = []
        ports = serial.tools.list_ports.comports(include_links=True)
        for port in ports:
            # Linux: skip devices without VID/PID
            if port.vid is None and str(port.device).startswith('/dev/ttyS'):
                continue
            vid = f"{port.vid:04X}" if port.vid is not None else "None"
            pid = f"{port.pid:04X}" if port.pid is not None else "None"   
            serial_no = f"{port.serial_number}" if port.serial_number is not None else "None"

            # Windows generates a fake serial number for FTDI devices.
            # check if the serial number is fake. 
            if os.name == "nt":
                fake = self._is_windows_serial_fake(port, silent=True)
                if not fake:
                    serial_no = f"{port.serial_number}"  # use the actual serial number
                else:
                    serial_no = "None"  # avoid Windows generated serial number
                

            # constract hardware identificator
            hwid_ = f"VID:PID:SER = {vid}:{pid}:{serial_no}" 
            if hwid_ in self.DEVICE_DIKT:
                device_list.append([port.device, self.DEVICE_DIKT[hwid_], hwid_ ])
            else:  
                device_list.append([port.device, "not in DEVICE_DIKT", hwid_])
        return device_list
        

    def _get_GPIB_connections(self):
        if self.rm is None:
            return[["None", "VISA Manager not initialized"]]
        
        device_list = []
        #rm = pyvisa.ResourceManager()
        resources = self.rm.list_resources()
        for res in resources:
            if res.startswith("ASRL"):
                continue

            if res in self.DEVICE_DIKT:
                device_list.append([res, self.DEVICE_DIKT[res]])
            else:
                device_list.append([res, "not in DEVICE_DIKT"])

        return device_list
    

    def _print_device_list(self, dv_list):
        for el in dv_list:
            if "not in DEVICE_DIKT" in el:
                print(el)
            else:
                print(f"{self.GREEN}{el}{self.RESET}")


    def print_connections(self):
        COM_list = self._get_COM_connections()
        GPIB_list = self._get_GPIB_connections()

        print(" COM connections ".center(50, '-'))
        self._print_device_list(COM_list)
        print(" GPIB/VISA connections ".center(50, '-'))
        self._print_device_list(GPIB_list)
        print(" print_connections() ended ".center(50, '-'))


    def _com_to_visa(self, port):
        port = str(port)
        if port.upper().startswith("COM"):
            # Windows: COM3 → ASRL3::INSTR
            port_number = port.upper().replace("COM", "").strip()
            return f"ASRL{port_number}::INSTR"
        else:
            # Linux with Symlink: /dev/ttyACM0 → ASRL/dev/ttyACM0::INSTR
            return f"ASRL{port}::INSTR"


    def get_COM_port(self):

        # test if hwid given
        if self.hwid is None:
            print(f"{self.RED}Error in get_COM_port() of BaseDevice")
            print(f"{self.RED} It is BaseDevice, no hwd defined, no connections {self.RESET}")
            return self
        # test if the devive known and in DEVICE_DIKT
        if self.hwid not in self.DEVICE_DIKT:
            print(f"{self.RED}Error in get_COM_port() of BaseDevice")
            print(f"Device {self.hwid} not in DEVICE_DIKT {self.RESET}")
            return self
        
        device_list = self._get_COM_connections()
        for dv in device_list:
            if dv[-1] == self.hwid:
                self.port = self._com_to_visa(dv[0])
                print(f"{self.GREEN}Found {self.name} on {self.port}{self.RESET}")
                return self
            
        self.port = None # if not found in connections 
        print(f"{self.RED}Error in get_COM_port() of BaseDevice")
        print(f"Device {self.name} with HWID {self.hwid} not found!")
        print(f"probably it is not connected to COM port{self.RESET}")
        return self


    def connect(self, silent=True):
        f_id = "\n BaseDevice.connect() "
        if self.port is None:
            print(f_id)
            print(f"{self.RED}Error: Port unknown. Run get_COM_port() first."
                  f"or set self.port property {self.RESET}")
            return self
        
        try: 
          #  self.connection = self.rm.open_resource(self.port, **self.CONNECTION_SETTINGS)
            self.__inst = self.rm.open_resource(self.port, **self.CONNECTION_SETTINGS)
            print(f"{self.GREEN}Connected to {self.name} on {self.port}{self.RESET}")
            self.after_connect(silent=silent)
        except Exception as e:
            print(f_id)
            print(f"{self.RED}Connection failed: {e}{self.RESET}")
            
        return self


    def after_connect(self, silent=True):
        '''hook for particular device connections'''
        print("BaseDevice after_connect")
        return self
    

    def disconnect(self):
        f_id = "\n BaseDevice.disconnect() "
        if self.__inst is None:
        # if self.connection is None: # it will initiate the print commands of self.connection if no connection
            print(f_id)
            print(f"{self.name}.connection=None, may be it was not open")
            return self
        else:
            try:
                # self.__inst.close()  # for Stefan scripts can be useful
                self.connection.close()
                print(f"{self.GREEN}[{self.name}] Connection closed.{self.RESET}")
                self.__inst = None
            except Exception as e:
                print(f_id)
                print(f"[{self.RED}{self.name}] Error at closing:{self.RESET} {e}")

            
            #finally:
            return self


if __name__ == "__main__":
    subprocess.run('cls' if os.name == 'nt' else 'clear', shell=True)
    tc = TerminalColours()
    print(f"{tc.CYAN}======== base_device.py module ========={tc.RESET}")      
    dvc = BaseDevice()


    dvc.print_com_info()
    dvc.print_connections()
    dvc.print_coulors()
